---
- name: Set /etc/hosts from Ansible hostgroups
  hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Jinja 2 template for /etc/hosts
      template:    
        dest: /etc/hosts 
        src: templates/hosts.j2
